# -*- mode: yaml; -*-
# vim:set shiftwidth=2 syntax=yaml:

image: ruby:2.7

stages:
  - prepare
  - build
  - test
  - deployment

cache:
  key: "$CI_PROJECT_PATH"
  paths:
    - .bundle/
    - doc/
    - vendor/

variables:
  BUNDLE_APP_CONFIG: .bundle

prepare:
  stage: prepare
  script:
    - gem update did_you_mean
    - gem update bundler
    - bundle config set deployment 'true'
    - bundle install --jobs $(nproc --ignore=1)

rake-test:
  stage: test
  script:
    - bundle exec rake test
